name: nutrition
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  camera: ^0.11.0+1
  http: ^1.2.2
  http_parser: ^4.0.2
  material_symbols_icons: ^4.2768.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  flutter_bloc: ^8.1.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter:
  assets:
    - assets/logo/
    - assets/icon/
    - assets/images/
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#DFFFEA"

flutter_native_splash:
  color: "#FCFDF6"
  color_dark: "#1A1C19"
  image: "assets/logo/light.png"
  image_dark: "assets/logo/dark.png"
  android: true
  ios: true
