name: nutrution
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  camera: ^0.11.0+1
  http: ^1.2.2
  http_parser: ^4.0.2
  material_symbols_icons: ^4.2768.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/logo/
  uses-material-design: true
